Changed for loading xml from ROS param(#119)
gazebosim/ros_gz pull request #120
Opened 2020-10-27 08:25 UTC by chama1176

I have fixed #119

2020-10-27 17:42 UTC, chapulina requested changes
Thank you for the PR, it looks good to me once the warning is fixed.

2020-10-27 17:42 UTC, chapulina commented on ros_ign_gazebo/src/create.cpp
> +
Can you fix this warning?

```
/code/ros_ign_gazebo/src/create.cpp:43:  Redundant blank line at the start of a code block should be deleted.  [whitespace/blank_line] [2]
```

2020-10-28 10:59 UTC, chama1176 commented on ros_ign_gazebo/src/create.cpp
> +
Thank you for checking.
I' ll fix it.

2020-10-29 15:47 UTC, chapulina approved these changes
I haven't tried the exact setup on #119, but I checked that the basic behaviour still works the same way, so I don't see a problem getting this in.

Thank you for the PR!

2020-10-29 15:49 UTC, merged