Add visualization_msgs/Marker
gazebosim/ros_gz pull request #136
Opened 2021-02-26 16:54 UTC by mjcarroll

# 🎉 Add visualization_msgs/Marker

## Summary

Add support for the visualization_msgs/Marker and visualization_msgs/MarkerArray types to the bridge.

## Test it

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-03-01 07:44 UTC, ahcorde requested changes

2021-03-01 07:44 UTC, ahcorde commented on ros_ign_bridge/src/convert.cpp
> +  switch(ros_msg.action)
visualization_msgs::Marker::MODIFY ?

2021-03-01 07:44 UTC, ahcorde commented on ros_ign_bridge/src/factories.cpp
> +    >("std_msgs/Bool", ign_type_name);
```suggestion
    >("std_msgs/ColorRGBA", ign_type_name);
```

2021-03-01 15:37 UTC, mjcarroll commented on ros_ign_bridge/src/convert.cpp
> +  switch(ros_msg.action)
Good catch, thanks.

2021-03-01 15:52 UTC, ahcorde approved these changes
but CI is failing 

```
anyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

2021-03-01 15:58 UTC, mjcarroll commented
> but CI is failing

I also remembered why I didn't have both `ADD` and `MODIFY` in there.  They map to the same value `0`.  You can't have multiple `cases` with the same value.  I'll revert that.

2021-03-01 15:59 UTC, ahcorde commented
can you add a comment ?

2021-03-03 07:22 UTC, ahcorde commented
@mjcarroll do we know how to proceed with Travis ?

2021-03-03 18:34 UTC, chapulina commented
I re-triggered Travis, and now the build fails:


```
Errors << ros_ign_bridge:make /root/catkin_ws/logs/ros_ign_bridge/build.make.000.log

/root/catkin_ws/src/code/ros_ign_bridge/src/convert.cpp: In function 'void ros_ign_bridge::convert_ros_to_ign(const ROS_T&, IGN_T&) [with ROS_T = visualization_msgs::Marker_<std::allocator<void> >; IGN_T = ignition::msgs::Marker]':

/root/catkin_ws/src/code/ros_ign_bridge/src/convert.cpp:1299:48: error: 'ARROW' is not a member of 'ignition::msgs::Marker'

       ign_msg.set_type(ignition::msgs::Marker::ARROW);

                                                ^~~~~

/root/catkin_ws/src/code/ros_ign_bridge/src/convert.cpp: In function 'void ros_ign_bridge::convert_ign_to_ros(const IGN_T&, ROS_T&) [with ROS_T = visualization_msgs::Marker_<std::allocator<void> >; IGN_T = ignition::msgs::Marker]':

/root/catkin_ws/src/code/ros_ign_bridge/src/convert.cpp:1438:34: error: 'CONE' is not a member of 'ignition::msgs::Marker'

     case ignition::msgs::Marker::CONE:

                                  ^~~~

/root/catkin_ws/src/code/ros_ign_bridge/src/convert.cpp:1442:34: error: 'ARROW' is not a member of 'ignition::msgs::Marker'

     case ignition::msgs::Marker::ARROW:

                                  ^~~~~

/root/catkin_ws/src/code/ros_ign_bridge/src/convert.cpp:1445:34: error: 'AXIS' is not a member of 'ignition::msgs::Marker'

     case ignition::msgs::Marker::AXIS:

                                  ^~~~
```

2021-03-08 06:46 UTC, ahcorde requested changes
CI is failing

2021-03-08 14:35 UTC, mjcarroll commented
Ah, so it looks like the difference is `citadel` vs `dome`, as the message has changed between the two releases.

2021-03-08 15:22 UTC, ahcorde approved these changes

2021-03-08 15:34 UTC, merged