Fix/default ign version
gazebosim/ros_gz pull request #145
Opened 2021-03-26 22:01 UTC by caioaamaral

# 🦟 Bug fix

Fixes #133 

## Summary
This change uses as the default version the dependency resolved by the package manifest (which uses ignition-gazebo3 for the foxy distro). This is accomplished by appending the flag `--force-version` (only when it's not already set) to the `ign_args`

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

- [ ] **Depends on**: ignitionrobotics/ign-tools#44 (to allow passing the major version only)

**Note to maintainers**: Remember to use **Squash-Merge**

2021-03-26 22:05 UTC, caioaamaral commented
I added to the checklist another pr which is required for this one work as planned (ignitionrobotics/ign-tools#44)

Is a unit test desired? (maybe we could test it by using specific configurations with the ci?)

2021-03-26 22:06 UTC, caioaamaral commented
@chapulina I've opened the PR to the wrong branch, could you please move it to the ros2 branch please?

2021-03-26 22:15 UTC, caioaamaral commented on ros_ign_gazebo/launch/ign_gazebo.launch.py
> +def __get_ign_gazebo_default_version(): # this will fail if the package build was performed with '--merge-install'
To the reviewer:

At least locally I couldn't find the package when my workspace was build with `--merge-install` flag, apparently the overlay did not work (the package manifest was not installed).

2021-03-29 06:26 UTC, ahcorde requested changes
do you mind to fix the conflicts with the main branch ?

2021-03-29 16:20 UTC, caioaamaral commented
> do you mind to fix the conflicts with the main branch ?

Done

2021-04-13 17:08 UTC, caioaamaral commented
Friendly ping.

I think this one is good to go now ignitionrobotics/ign-tools#44 is merged

2021-04-13 21:48 UTC, chapulina commented
Thanks, @caioaamaral , we'll take a look soon. Note that we'll need an `ign-tools` release, and also upload the released version to packages.ros.org, before this can be merged.

2021-04-27 01:46 UTC, chapulina commented
I'm getting an error on launch, I tried compiling with `--merge-install` and without. Do you know what's happening?

```
  File "/home/chapulina/dev_focal/ws_foxy/install/ros_ign_gazebo/share/ros_ign_gazebo/launch/ign_gazebo.launch.py", line 39, in generate_lau
nch_description
    OpaqueFunction(__get_ign_args)
TypeError: __init__() takes 1 positional argument but 2 were given
```

2021-06-17 22:36 UTC, chapulina commented
@caioaamaral , are you still working on this PR?

2021-06-21 20:27 UTC, caioaamaral commented
> @caioaamaral , are you still working on this PR?

Sorry for the delay. I'll have a look by the end of this week

2021-11-09 05:42 UTC, chapulina commented
Hi @caioaamaral , I'm closing this due to inactivity, but feel free to reopen if you start working on it again. Thanks!

2021-11-09 05:42 UTC, closed without merging