Joint states tutorial
gazebosim/ros_gz pull request #156
Opened 2021-05-27 14:11 UTC by vatanaksoytezer

Adds an rrbot model to demos and shows the usage of joint_states plugin.

2021-05-27 15:58 UTC, ahcorde requested changes
You are adding here the URDF and the SDF and using it both in the launch file. I don't like this approach because if you modify one you must need to modify the other one. You should use only the URDF, with xacro (which is imported but not used) you can convert the URDF and uing it to spawn the model. In this [file](https://github.com/ros-simulation/gazebo_ros_demos/blob/a5b8877fc8398e044e4aedccf69afb6c39ee298b/rrbot_gazebo/launch/rrbot_world.launch.py) you can find how to do it.

Another question that I open here it's that the `rrbot.urdf` should live only in one repository we should not copy this file in every repo that make use of it.

2021-05-27 15:58 UTC, ahcorde commented on ros_ign_gazebo_demos/launch/joint_states.launch.py
> +        parameters=[]
remove

2021-05-27 15:58 UTC, ahcorde commented on ros_ign_gazebo_demos/launch/joint_states.launch.py
> +    # rrbot_sdf_path =  os.path.join(pkg_ros_ign_gazebo_demos, 'models', 'rrbot2.sdf')
remove

2021-05-27 15:58 UTC, ahcorde commented on ros_ign_gazebo_demos/launch/joint_states.launch.py
> +    print(rrbot_sdf_path)
remove

2021-05-27 15:58 UTC, ahcorde commented on ros_ign_gazebo_demos/launch/joint_states.launch.py
> +                )
parentheses at the same indentation as the others

2021-05-27 15:58 UTC, ahcorde commented on ros_ign_gazebo_demos/launch/joint_states.launch.py
> +import xacro
you are importing here xacro, but you are not using it

2021-05-27 16:00 UTC, ahcorde requested changes
You should also sign the [PR](https://github.com/ignitionrobotics/ros_ign/pull/156/checks?check_run_id=2685739378)

2021-05-27 16:01 UTC, ahcorde commented
@vatanaksoytezer, I have seen in your profile that you are working for Picknik maybe we can speed up this other PR https://github.com/ros-simulation/gazebo_ros_demos/pull/41 where I think the rrobot description should live.

2021-05-27 16:49 UTC, vatanaksoytezer commented
> @vatanaksoytezer, I have seen in your profile that you are working for Picknik maybe we can speed up this other PR [ros-simulation/gazebo_ros_demos#41](https://github.com/ros-simulation/gazebo_ros_demos/pull/41) where I think the rrobot description should live.

Sure I can ping Dave internally.

2021-05-27 16:50 UTC, vatanaksoytezer commented on ros_ign_gazebo_demos/launch/joint_states.launch.py
> +    # rrbot_sdf_path =  os.path.join(pkg_ros_ign_gazebo_demos, 'models', 'rrbot2.sdf')
Oops forgot those in cleanup

2021-05-27 16:56 UTC, vatanaksoytezer commented
> Another question that I open here it's that the rrbot.urdf should live only in one repository we should not copy this file in every repo that make use of it.

I would agree that but I really wouldn't want to make `ign_gazebo_demos` depend to `gazebo_ros_demos` for rrbot only. Maybe you guys can consider opening up a rrbot description and depend on that?

2021-05-27 17:11 UTC, vatanaksoytezer commented
> You are adding here the URDF and the SDF and using it both in the launch file. I don't like this approach because if you modify one you must need to modify the other one. You should use only the URDF, with xacro (which is imported but not used) you can convert the URDF and uing it to spawn the model. In this [file](https://github.com/ros-simulation/gazebo_ros_demos/blob/a5b8877fc8398e044e4aedccf69afb6c39ee298b/rrbot_gazebo/launch/rrbot_world.launch.py) you can find how to do it.

@ahcorde Follow up question on this one. Since this is to demonstrate the usage of `joint_states` plugin in ignition, where should I put the plugin if I don't have the sdf file? I was mostly looking up for @chapulina 's `dolly` package where she also defines the robot from  an sdf file.

2021-05-27 17:13 UTC, vatanaksoytezer commented
Another problem that I just realised is if rrbot_description live somewhere else and contains `gazebo` and `ros2_control` stuff that is not compatible with ignition (yet), wouldn't be problematic?

2021-05-27 17:48 UTC, vatanaksoytezer commented
@ahcorde update: 

- Pinged Dave on gazebo PR.
- Signed off the commits and cleaned up stuff, except for the sdf (see my comments above)

2021-05-28 14:38 UTC, vatanaksoytezer commented
Ignore the comments above on sdf, just figured that out. I'll fix in and send updates soon

2021-05-28 19:03 UTC, vatanaksoytezer commented
This should work, but the colors (and I think frictions) are not parsed correctly to ign. If you point me a way I can fix it right away

2021-06-10 08:53 UTC, ahcorde commented
@vatanaksoytezer, I can see the color in ignition 

![Selección_104](https://user-images.githubusercontent.com/1933907/121495469-edd24a00-c9d9-11eb-8fc3-ce08df4cf428.png)

2021-06-10 08:54 UTC, ahcorde approved these changes
LGTM

2021-06-10 17:11 UTC, merged