Fix catkin_testing warning
gazebosim/ros_gz pull request #163
Opened 2021-06-13 00:25 UTC by Tobias-Fischer

This PR fixes the following warning:
```
2021-06-13T00:21:23.1437210Z CMake Warning at /usr/local/miniconda/conda-bld/ros_1623543542471/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/share/catkin/cmake/test/tests.cmake:50 (message):
2021-06-13T00:21:23.1472630Z   add_rostest() should only be used inside a conditional block which checks
2021-06-13T00:21:23.1500790Z   that testing is enabled:
2021-06-13T00:21:23.1545630Z 
2021-06-13T00:21:23.1547960Z   if(CATKIN_ENABLE_TESTING)
2021-06-13T00:21:23.1573800Z 
2021-06-13T00:21:23.1574440Z     add_rostest(...)
2021-06-13T00:21:23.1637110Z 
2021-06-13T00:21:23.1662240Z   endif()
2021-06-13T00:21:23.1668530Z 
```

2021-06-14 07:17 UTC, ahcorde approved these changes

2021-06-14 07:17 UTC, ahcorde requested changes
Do you mind to [sign the commit](https://github.com/ignitionrobotics/ros_ign/pull/163/checks?check_run_id=2811630010) ?

2021-06-14 22:26 UTC, Tobias-Fischer commented
Done

2021-06-15 07:37 UTC, ahcorde approved these changes

2021-06-15 07:49 UTC, merged