Add support for bridging NavSat
gazebosim/ros_gz pull request #224
Opened 2022-03-11 19:45 UTC by TyHowellWork

# 🎉 New feature

Closes #<NUMBER>

## Summary
Adds two-way bridge for NavSat messages between ROS and IGN along with a demo launch file.

## Test it
Test IGN->ROS by running `roslaunch ros_ign_gazebo_demos navsat.launch`.
Test ROS->IGN by `roslaunch ros_ign_gazebo_demos navsat.launch` and `ign topic -t /navsat -e`
```
rostopic pub -r 1 /navsat sensor_msgs/NavSatFix "header:
  seq: 10
  stamp: {secs: 10, nsecs: 0}
  frame_id: 'back_to_ign'
status: {status: 0, service: 0}
latitude: 10.0
longitude: 10.0
altitude: 10.0
position_covariance: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
position_covariance_type: 0"
```
Even using the contributing guides I was unable to get codecheck or the tests running.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [x] Added example and/or tutorial
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-03-14 23:31 UTC, chapulina requested changes
Thanks for the PR. The implementation, test and example look great!

The only catch is that this branch is supported with both Citadel and Fortress, but the `NavSat` message and the `NavSat` sensor are only available from Fortress. So we have a couple of options:

* Add `ifdef`s so the `NavSat` is only present on `IGN_MSGS_VER >= 8`
* Or backport the `NavSat` message to `ign-msgs5` - while this is trivial, backporting the `NavSat` sensor itself isn't. It shouldn't hurt having the message there though.

In any case, we should add a note to `ros_ign_gazebo_demos/README.md` that the GNSS example only works from Fortress.

2022-03-15 11:48 UTC, ahcorde requested changes, later dismissed

2022-03-15 11:48 UTC, ahcorde commented on ros_ign_bridge/test/test_utils.h
> +    EXPECT_FLOAT_EQ(expected_msg.altitude,           _msg.altitude);
```suggestion
    EXPECT_FLOAT_EQ(expected_msg.latitude, _msg.latitude);
    EXPECT_FLOAT_EQ(expected_msg.longitude, _msg.longitude);
    EXPECT_FLOAT_EQ(expected_msg.altitude, _msg.altitude);
```

2022-03-15 11:48 UTC, ahcorde commented on ros_ign_bridge/test/test_utils.h
> +    _msg.position_covariance = {1, 2, 3, 4, 5, 6, 7, 8, 9};
```suggestion
    _msg.altitude                  = 0.00;
    _msg.position_covariance       = {1, 2, 3, 4, 5, 6, 7, 8, 9};
```

2022-03-15 13:27 UTC, TyHowellWork commented
@chapulina @ahcorde Thanks for the reviews I should have a fix :) by the end of the day.

2022-03-16 13:54 UTC, TyHowellWork commented
ign-msgs5 [PR](https://github.com/ignitionrobotics/ign-msgs/pull/231) has been submitted that backports NavSat message only.

2022-03-16 15:56 UTC, chapulina commented
> ign-msgs5 https://github.com/ignitionrobotics/ign-msgs/pull/231 has been submitted that backports NavSat message only.

Thanks! Here are the next steps:

- [ ] Release `ign-msgs5` with the `NavSat` message: https://github.com/ignitionrobotics/ign-msgs/pull/232
- [ ] Pull that into packages.ros.org with reprepro
- [ ] Run CI on this PR

2022-04-22 22:15 UTC, chapulina approved these changes
Ready! Thanks for the wait!

2022-04-22 22:16 UTC, merged