Ahcorde/galactic to ros2
gazebosim/ros_gz pull request #228
Opened 2022-03-29 16:47 UTC by ahcorde

# ➡️ Forward port

Port galactic to ros2

Branch comparison: https://github.com/ignitionrobotics/ros_ign/compare/ros2...galactic

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

2022-03-29 18:12 UTC, mjcarroll approved these changes

2022-03-30 19:35 UTC, chapulina requested changes

2022-03-30 19:35 UTC, chapulina commented on .github/workflows/ros2-ci.yml
> +            ros-distro: "galactic"
This branch should be testing `rolling`

2022-03-30 21:07 UTC, chapulina approved these changes
LGTM, just pending #219

2022-04-22 22:19 UTC, chapulina commented
@ros-pull-request-builder retest this please

2022-04-22 22:36 UTC, chapulina commented
No new test failures, merging

2022-04-22 22:36 UTC, merged