Add node component and yaml-configured bridge node
gazebosim/ros_gz pull request #238
Opened 2022-04-07 18:37 UTC by mjcarroll

# 🎉 New feature

## Summary

Primarily introducing a yaml-configured node, but some more refactoring to clean things up.

1. Adds a [component](https://docs.ros2.org/latest/api/rclcpp_components/) version of bridge called `ros_ign_bridge::RosIgnBridge`
  * This component can be used via the stand-alone executable `./bridge_node` or as part of a component container.
  *  This follows best practices for ROS2 going forward.
2. Adds a `yaml`-based configuration that exposes all features of the bridge.  Passed in via a `config_file` parameter.  This should allow us to bypass some of the ERB-and-remapping that we have done on various projects,..

Example yaml configuration for 5 topics below
```
 # Set just topic name, applies to both
- topic_name: "chatter" 
  ros_type_name: "std_msgs/msg/String"
  ign_type_name: "ignition.msgs.StringMsg"

# Set just ROS topic name, applies to both
- ros_topic_name: "chatter_ros" 
  ros_type_name: "std_msgs/msg/String"
  ign_type_name: "ignition.msgs.StringMsg"

# Set just IGN topic name, applies to both
- ign_topic_name: "chatter_ign" 
  ros_type_name: "std_msgs/msg/String"
  ign_type_name: "ignition.msgs.StringMsg"

# Set each topic name explicitly
- ros_topic_name: "chatter_both_ros"
  ign_topic_name: "chatter_both_ign" 
  ros_type_name: "std_msgs/msg/String"
  ign_type_name: "ignition.msgs.StringMsg"

# Full set of configurations
- ros_topic_name: "ros_chatter"
  ign_topic_name: "ign_chatter"
  ros_type_name: "std_msgs/msg/String"
  ign_type_name: "ignition.msgs.StringMsg"
  subscriber_queue: 5
  publisher_queue: 6
  lazy: true
```

3. Refactored `parameter_bridge` and `static_bridge` to use the component.
4. Put `ros_ign_bridge::RosIgnBridge` in the public API so it can be used downstream.

## Test it

Unit tests have been added for the new configuration functionality, no other tests should regress.

Test the new configuration with:
```
./bridge_node --ros-args -p config_file:=$WORKSPACE/ros_ign/ros_ign_bridge/test/config/full.yaml 
```

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-04-18 22:02 UTC, iche033 reviewed
There are some conflicts with `galactic` branch

The `Gpr__ros_ign__ubuntu_focal_amd64`  build complains about missing `rclcpp_components` package so I think that extra dependency needs to be added to CI.

yaml based configuration is great new feature. Maybe add some info to `README.md`?

2022-04-18 22:02 UTC, iche033 commented on ros_ign_bridge/CMakeLists.txt
> -  lazy_static_bridge
I think its fine to remove this executable if we have not made a release with this yet.

2022-04-18 22:02 UTC, iche033 commented on ros_ign_bridge/src/bridge_handle.hpp
>    /// \param[in] is_lazy True for "lazy" subscriptions. (Default: false)
update doxygen param

2022-04-18 22:02 UTC, iche033 commented on ros_ign_bridge/src/ros_ign_bridge.cpp
> +  this->declare_parameter<int>("subscription_heartbeat", 1000);
this parameter looks like something new? Document this in `README.md`?

2022-04-20 08:39 UTC, ahcorde requested changes

2022-04-20 08:39 UTC, ahcorde commented on ros_ign_bridge/CMakeLists.txt
> -find_package(rclcpp REQUIRED)
why do you split this in two sections ? alphabetize ?

2022-04-20 08:39 UTC, ahcorde commented on ros_ign_bridge/README.md
> +language. In this case, the ros_ign bridge supports using a YAML file to configure the
```suggestion
language. In this case, the `ros_ign` bridge supports using a YAML file to configure the
```

2022-04-20 08:39 UTC, ahcorde commented on ros_ign_bridge/README.md
> +```
```suggestion
```yaml
```

2022-04-20 08:39 UTC, ahcorde commented on ros_ign_bridge/README.md
> +```
```suggestion
```bash
```

2022-04-20 08:39 UTC, ahcorde commented on ros_ign_bridge/include/ros_ign_bridge/bridge_config.hpp
> +
```suggestion
```

2022-04-20 08:39 UTC, ahcorde commented on ros_ign_bridge/src/bridge_config.cpp
> +
```suggestion
```

2022-04-20 08:39 UTC, ahcorde commented on ros_ign_bridge/src/ros_ign_bridge.cpp
> +
```suggestion
```

2022-04-20 08:39 UTC, ahcorde commented on ros_ign_bridge/src/ros_ign_bridge.cpp
> +
```suggestion
```

2022-06-16 08:23 UTC, ahcorde approved these changes

2022-06-16 20:23 UTC, merged