Fix catkin dependencies for demos
gazebosim/ros_gz pull request #277
Opened 2022-07-22 11:21 UTC by rsinnet

Add missing dependencies to for ros_ign_gazebo_demos to package.xml.
# 🦟 Bug fix

Fixes: #276

## Summary
Added missing packages to package.xml for demos package.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [x] Updated documentation (as needed)
- [x] Updated migration guide (as needed)
- [x] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

2022-07-22 13:03 UTC, ahcorde requested changes
I don't think we need to add some of the dependencies. For example `*_controllers` is something that is used with `gz_ros2_control` but these examples are not using this library.

Can you point me where is this package using all these controllers  ?

2022-07-24 22:13 UTC, rsinnet commented
> I don't think we need to add some of the dependencies. For example `*_controllers` is something that is used with `gz_ros2_control` but these examples are not using this library.
> 
> Can you point me where is this package using all these controllers ?

Oops, sorry! I think I mixed this up with: https://github.com/gazebosim/ros_gz/pull/277

I updated this current PR with the single missing dependency on rqt_topic.

2022-07-26 08:21 UTC, ahcorde approved these changes

2022-07-26 08:31 UTC, merged

2022-07-26 13:08 UTC, rsinnet commented
> > I don't think we need to add some of the dependencies. For example `*_controllers` is something that is used with `gz_ros2_control` but these examples are not using this library.
> > Can you point me where is this package using all these controllers ?
> 
> Oops, sorry! I think I mixed this up with: #277
> 
> I updated this current PR with the single missing dependency on rqt_topic.

I see I put the wrong issue link. For future reference, this is the other one I was working on simultaneously: https://github.com/ros-controls/ign_ros_control/pull/2