Add ROS2 version of Stopwatch
gazebosim/ros_gz pull request #287
Opened 2022-08-16 20:07 UTC by andermi

# 🎉 New feature

## Summary
Add a ROS2 version of `math::Stopwatch` that can make use of `rclcpp::Clock` and sim time via `/clock`

## Test it
Check `test/test_stopwatch.cpp` for examples

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-08-26 05:40 UTC, quarkytale approved these changes
lgtm

2022-08-26 06:38 UTC, ahcorde requested changes

2022-08-26 06:38 UTC, ahcorde commented on ros_ign_gazebo/CMakeLists.txt
> +  function(gz_add_gtest TEST_NAME)
I don't think it's a good idea to add this logic here, can you simplify this?

2022-08-26 06:38 UTC, ahcorde commented on ros_ign_gazebo/include/ros_ign_gazebo/Stopwatch.hpp
> +  Stopwatch(const Stopwatch & _watch);
Please use this style
```suggestion
  /// \brief Copy constructor
  /// \param[in] _watch The stop watch to copy.
  public: Stopwatch(const Stopwatch & _watch);
```

2022-08-26 06:38 UTC, ahcorde commented on ros_ign_gazebo/CMakeLists.txt
> +  # Helper function to generate gtest
simplify this logic

2022-09-01 03:40 UTC, quarkytale commented on ros_ign_gazebo/include/ros_ign_gazebo/Stopwatch.hpp
> +  Stopwatch(const Stopwatch & _watch);
Uncrustify is failing with that style though

2022-09-02 09:23 UTC, ahcorde requested changes

2022-09-02 09:23 UTC, ahcorde commented on ros_ign_gazebo/CMakeLists.txt
> +
```suggestion
add_library(Stopwatch src/Stopwatch.cpp)
ament_target_dependencies(Stopwatch
  rclcpp
)

target_include_directories(Stopwatch PUBLIC
  $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
  $<INSTALL_INTERFACE:include>
)

install(DIRECTORY include/${PROJECT_NAME}/
  DESTINATION include/${PROJECT_NAME}
)

```

2022-09-02 09:23 UTC, ahcorde commented on ros_ign_gazebo/CMakeLists.txt
> +
```suggestion

  # GTest
  find_package(ament_cmake_gtest REQUIRED)
  ament_find_gtest()

  ament_add_gtest_executable(test_stopwatch
    test/test_stopwatch.cpp
  )
  
  ament_target_dependencies(test_stopwatch rclcpp)

  target_include_directories(test_stopwatch PUBLIC
      $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
      $<INSTALL_INTERFACE:include>
   )

  target_link_libraries(test_stopwatch
    Stopwatch
  )

  install(
    TARGETS test_stopwatch
    DESTINATION lib/${PROJECT_NAME}
  )
  ament_add_gtest_test(test_stopwatch)

```

2022-09-02 09:23 UTC, ahcorde commented on ros_ign_gazebo/include/ros_ign_gazebo/Stopwatch.hpp
> +  void SetClock(rclcpp::Clock::SharedPtr _clock);
```suggestion
    /// param[in] _clock
    void SetClock(rclcpp::Clock::SharedPtr _clock);
```

2022-09-02 09:23 UTC, ahcorde commented on ros_ign_gazebo/src/Stopwatch.cpp
> +      this->dataPtr->stopTime - this->dataPtr->startTime;
```suggestion
    this->dataPtr->runDuration = this->dataPtr->runDuration +
      this->dataPtr->stopTime - this->dataPtr->startTime;
```

2022-09-02 09:23 UTC, ahcorde commented on ros_ign_gazebo/test/test_stopwatch.cpp
> +// Copyright 2020 Open Source Robotics Foundation, Inc.
```suggestion
// Copyright 2022 Open Source Robotics Foundation, Inc.
```

2022-09-02 09:26 UTC, ahcorde requested changes
Linters are failing 

```
4: /github/home/ws/src/ros_gz/ros_ign_gazebo/src/Stopwatch.cpp:35:  Do not leave a blank line after "public:"  [whitespace/blank_line] [3]
4: /github/home/ws/src/ros_gz/ros_ign_gazebo/src/Stopwatch.cpp:64:  Do not leave a blank line after "public:"  [whitespace/blank_line] [3]
4: /github/home/ws/src/ros_gz/ros_ign_gazebo/src/Stopwatch.cpp:67:  Do not leave a blank line after "public:"  [whitespace/blank_line] [3]
4: /github/home/ws/src/ros_gz/ros_ign_gazebo/src/Stopwatch.cpp:70:  Do not leave a blank line after "public:"  [whitespace/blank_line] [3]
4: /github/home/ws/src/ros_gz/ros_ign_gazebo/src/Stopwatch.cpp:73:  Do not leave a blank line after "public:"  [whitespace/blank_line] [3]
4: /github/home/ws/src/ros_gz/ros_ign_gazebo/src/Stopwatch.cpp:76:  Do not leave a blank line after "public:"  [whitespace/blank_line] [3]
```

```
The following tests FAILED:
	  4 - cpplint (Failed)
	  6 - uncrustify (Failed)
Errors while running CTest
--- stderr: ros_ign_gazebo
```

2022-09-02 18:13 UTC, andermi commented
> Linters are failing

moving to gazebo-style with `public:` on each member caused the linters to fail

2022-09-05 08:15 UTC, ahcorde approved these changes

2022-09-05 08:22 UTC, merged