Fixing gazebo lidar sensor output to ROS topic
gazebosim/ros_gz pull request #326
Opened 2022-11-02 21:17 UTC by ConnorDTaylor

# 🦟 Bug fix

Fixes # 1

## Summary
I noticed that the GPU LIDAR sensor would only pass one horizontal line of ranges and intensities from Gazebo to ROS instead of all of the ranges defined by horizontal*vertical counts. So, I changed this in the source code to allow all of these ranges to be passed. 
To replicate before: Simply put a GPU lidar sensor into the environment and try to use the bridge in the launch file to pass the gazebo messages to ROS2. 

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-11-03 12:12 UTC, mjcarroll commented
Thanks for the contribution.  Two things:

1. Can you signoff your commits so that DCO will pass?

```
To add your Signed-off-by line to every commit in this branch:
Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
In your local branch, run: git rebase HEAD~2 --signoff
Force push your changes to overwrite the branch: git push --force-with-lease origin ros2
```

2. Can you add a test with some vertical elements set so that we can be sure to exercise this?

2022-11-03 14:28 UTC, ConnorDTaylor commented
I believe I did everything requested. I added a test environment that can be run with the command: "ros2 launch ros_gz_sim_demos lidar_test.launch.py" once this is running you can then run "ros2 topic echo /lidar" and "gz topic --echo --topic /lidar" to check that the messages being passed are the same. 

If I didn't do something I thought I did please let me know! I am new to using GitHub in this capacity.

2022-11-03 14:30 UTC, mjcarroll commented
> If I didn't do something I thought I did please let me know! I am new to using GitHub in this capacity.

Tests look good, but I think we are still having an issue with DCO.  Can you follow the instructions here and force push to get that resolved? https://github.com/gazebosim/ros_gz/pull/326/checks?check_run_id=9274824771

2022-11-03 14:42 UTC, ConnorDTaylor commented
Will do, I did HEAD~2 from what you said, but the link says HEAD~3. So I tried that. Hopefully, it worked.

2022-11-03 14:44 UTC, mjcarroll commented
Yep, looks good now, thanks.

2022-11-07 11:33 UTC, ahcorde requested changes

2022-11-07 11:33 UTC, ahcorde commented on ros_gz_sim_demos/launch/lidar_test.launch.py
> +# Copyright 2019 Open Source Robotics Foundation, Inc.
```suggestion
# Copyright 2022 Open Source Robotics Foundation, Inc.
```

2022-11-07 11:33 UTC, ahcorde commented on ros_gz_sim_demos/launch/lidar_test.launch.py
> +       # FIXME: Generate new RViz config once this demo is usable again
remove traces that are not related

2022-11-07 11:33 UTC, ahcorde commented on ros_gz_sim_demos/launch/lidar_test.launch.py
> +    # FIXME: need a SDF file (gpu_lidar.sdf) inside ros_gz_point_cloud/
remove

2022-11-07 11:33 UTC, ahcorde commented on ros_gz_sim_demos/models/lidar_block/model.sdf
> +<?xml version='1.0'?>
indent the file properly

2022-11-07 11:33 UTC, ahcorde commented on ros_gz_sim_demos/worlds/lidar_test.sdf
> +<?xml version="1.0" ?>
indent the file properly

is it the comment relevant for this demo?

2022-12-05 13:37 UTC, quentingllmt commented
Friendly message to show my interest. When do you plan to merge ?
Will it be backported to galactic ? 
Thanks !

2022-12-05 13:44 UTC, ConnorDTaylor commented
> Friendly message to show my interest. When do you plan to merge ? Will it be backported to galactic ? Thanks !

I don't know why it hasn't been merged, no one has told me to fix anything and i'm not the most proficient github user so it's possible im missing something. 
I didn't plan on backporting this, I am working on Humble with Gazebo Garden. Though I I imagine fixing this problem is probably the same steps I took for this distro combination. So you should be able to just duplicate my changes. If you have any questions about it I can try to answer them, just shoot me an email.

2022-12-05 14:38 UTC, ahcorde reviewed
uncrustify is still failing https://github.com/gazebosim/ros_gz/actions/runs/3411060268/jobs/5787829085

2022-12-05 14:56 UTC, ahcorde commented
I tested your code with the example and it's not working properly

I would expect something like this:
![RViz-_002](https://user-images.githubusercontent.com/1933907/205668098-1a6f02e4-9db0-4987-bf9c-f2d7e54242c5.png)

But with your code I get:
![RViz-_001](https://user-images.githubusercontent.com/1933907/205668122-75a70d15-e898-48b8-8d6a-98be6a48555e.png)

2023-02-13 20:25 UTC, azeey commented
Looks like there are some linter issues and maybe some functionality issue here. @ConnorDTaylor have you had a chance to take a look?

2023-04-17 15:43 UTC, mjcarroll commented
@ConnorDTaylor I thought about this a little more and realized that this approach is incorrect.  The `LaserScan` message is only intended to represent a 2d scanning lidar, like a Hokuyo or SICK sensor.  In order to get data from a 3d scanning lidar (eg velodyne/ouster), then you want to use a PointCloud based message.

The PointCloud message can additionally encode sequence/ring/intensity in the additional channels, and can maintain the structure by using a "sparse" point cloud (missing points are marked nan), or can be more space efficient by using a "dense" point cloud (no nans, but loses scan structure).

2023-04-17 15:43 UTC, mjcarroll commented
If you have further issues, please let us know.

2023-04-17 15:43 UTC, closed without merging