Introduce WrenchStamped into bridge
gazebosim/ros_gz pull request #327
Opened 2022-11-04 16:23 UTC by livanov93

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

# 🎉 New feature

## Summary
Introduces conversion between `geometry_msgs::msg::WrenchStamped` and `ignition_msgs.msg.Wrench`.

## Test it

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-11-07 11:27 UTC, ahcorde requested changes
LGTM, do yu mind to add a entry in the `ros_gz_bridge/README.md` ?

2022-11-07 11:30 UTC, ahcorde requested changes
tests are also failing (uncrustify at least)

https://github.com/gazebosim/ros_gz/actions/runs/3395417704/jobs/5649418290

2023-02-07 17:49 UTC, livanov93 commented
@ahcorde friendly ping for a review. I improved `ros_gz_bridge/README.md` and fixed the linters. (CI will confirm after you enable it)

2023-02-08 09:40 UTC, ahcorde approved these changes

2023-02-08 09:40 UTC, merged

2023-02-08 09:40 UTC, ahcorde commented
I will create a forward port soon. Thank you for your contribution @livanov93

2023-02-25 15:41 UTC, xibeisiber commented
When will this change be forwarded to the ubuntu repository?