Add QoS profile parameter to image bridge
gazebosim/ros_gz pull request #335
Opened 2022-12-05 18:23 UTC by sea-bass

🎉 New feature

Closes #<NUMBER>

## Summary
This PR modifies the `image_bridge` node in the `ros_gz_image` package to optionally specify a different (non-default) [QoS profile](https://github.com/ros2/rmw/blob/rolling/rmw/include/rmw/qos_profiles.h). This was motivated by the fact that we (and presumably many others) want to use the "sensor data" QoS profile.

This exposes a new string parameter in the node named `qos` which defaults to `default`. This should be the same behavior as the original implementation of `image_bridge.cpp`.

## Test it
To test this, you can run an image bridge:

```bash
ros2 run ros_gz_image image_bridge /topic1 /topic2
ros2 run ros_gz_image image_bridge /topic1 /topic2 --ros-args qos:=sensor_data
```

or in e.g. a Python launch file:

```python
bridge_node = Node(
        package="ros_gz_image",
        executable="image_bridge",
        name="my_bridge",
        arguments=["/topic1",  "/topic2"],
        parameters=[{"qos": "sensor_data"}],
    )
```

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

# ➡️ Forward port

Port <FROM_BRANCH> to <TO_BRANCH>

Branch comparison: https://github.com/gazebosim/<REPO>/compare/<TO_BRANCH>...<FROM_BRANCH>

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

# 🎈 Release

Preparation for <X.Y.Z> release.

Comparison to <x.y.z>: https://github.com/gazebosim/<REPO>/compare/<LATEST_TAG_BRANCH>...<RELEASE_BRANCH>

Needed by <PR(s)>

## Checklist
- [ ] Asked team if this is a good time for a release
- [ ] There are no changes to be ported from the previous major version
- [ ] No PRs targeted at this major version are close to getting in
- [ ] Bumped minor for new features, patch for bug fixes
- [ ] Updated changelog
- [ ] Updated migration guide (as needed)
- [ ] Link to PR updating dependency versions in appropriate repository in [gazebo-release](https://github.com/gazebo-release) (as needed): <LINK>

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-12-06 07:09 UTC, ahcorde requested changes
can you add some documentation in the README.md of this packages?

2022-12-06 08:24 UTC, ahcorde requested changes
`cpplint` is failing too
```bash
3: /github/home/ws/src/ros_gz/ros_gz_image/src/image_bridge.cpp:21:  Found C system header after C++ system header. Should be: image_bridge.h, c system, c++ system, other.  [build/include_order] [4]
```

2022-12-06 14:43 UTC, sea-bass commented
> `cpplint` is failing too
> 
> ```shell
> 3: /github/home/ws/src/ros_gz/ros_gz_image/src/image_bridge.cpp:21:  Found C system header after C++ system header. Should be: image_bridge.h, c system, c++ system, other.  [build/include_order] [4]
> ```

Somehow this issue was there for the code even without my modifications. Anyways, I've rearranged it and got rid of this check failing locally. Added doc as well.

2022-12-15 00:57 UTC, sea-bass commented
Anything else blocking kicking off CI? I think I got all the changes.

2023-02-07 17:56 UTC, livanov93 commented
> Anything else blocking kicking off CI? I think I got all the changes.

@ahcorde Let's merge this one as we are in the new year now. Anything that needs attention from your perspective?

2023-02-08 09:24 UTC, ahcorde approved these changes

2023-02-08 09:24 UTC, merged