allow converting from/to TwistWithCovarianceStamped
gazebosim/ros_gz pull request #374
Opened 2023-03-15 13:51 UTC by ejalaa12

# 🎉 New feature

Allows converting from/to TwistWithCovarianceStamped

## Summary

`ros_gz_bridge` allows converting `gz.msgs.TwistWithCovariance` <-> `geometry_msgs.msg.TwistWithCovariance`.

However the `gz.msgs.TwistWithCovariance` also contains a header and stamp. So it could be converted to a `geometry_msgs.msg.TwistWithCovariance**Stamped**`.

This PR implements that conversion. It is now possible to convert either to/from:
- `geometry_msgs.msg.TwistWithCovariance`
- `geometry_msgs.msg.TwistWithCovarianceStamped`.

Note: I also have a backport of that commit to the humble branch, should I open it after this PR is done ?

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2023-03-20 21:20 UTC, adityapande-1995 requested changes
Thanks for adding this ! I'd like to have explicit tests where we puslish a msg from gz trasnport and check it in a ros subscriber, and the other way round : publishing a ros message and checking in a gz subscriber. 

Specifically, let's ahve tests here : 
- ros_ign_bridge/test/subscribers/ros_subscriber/geometry_msgs_subscriber.cpp
- ros_ign_bridge/test/subscribers/ign_subscriber.cpp

These are the launch files that enable that : 
- ros_ign_bridge/test/launch/test_ign_subscriber.launch.py
- ros_ign_bridge/test/launch/test_ros_subscriber.launch.py

I haven't tested this locally, but we might need some changes here as well : ros_ign_bridge/src/factories/geometry_msgs.cpp

Secondly, I can see we can add PoseWithCovarianceStamped in a similar fashion. Though not required in this PR, could you add a ticket for this ?

Third, this would require a new message definition in gz-msgs. Now that I think about it, TwistWithCovariance does have a header, maybe it is not populated when converting. How about if we just populate it instead of adding a new message ?

2023-03-20 21:20 UTC, adityapande-1995 commented on ros_gz_bridge/README.md
> +| ros_gz_interfaces/msg/VideoRecord            | ignition::msgs::VideoRecord            |
Could you fix the vertical table alignment and keep the namespace as "gz::" ?

2023-04-11 14:34 UTC, ejalaa12 commented on ros_gz_bridge/README.md
> +| ros_gz_interfaces/msg/VideoRecord            | ignition::msgs::VideoRecord            |
Nice catch, I was probably working on a wrong branch with ignition instead of gz. I'll a an amend commit to clean this up

2023-04-11 14:56 UTC, ejalaa12 commented
sorry for the delay in answer @adityapande-1995 
I just pushed the changes for the readme.
I also opened up a PR for the PoseWithCovarianceStamped as well.

2023-04-24 08:08 UTC, ejalaa12 commented
@adityapande-1995 Did you have time to review my changes ?

2023-05-08 22:02 UTC, ahcorde requested changes
conflicts

2023-05-11 17:34 UTC, ejalaa12 commented
@ahcorde just fixed the conflicts

2023-05-11 21:10 UTC, ahcorde approved these changes
@adityapande-1995 do you mind to take another look ?

2023-05-22 15:33 UTC, adityapande-1995 approved these changes
Looks good with conflicts resolved in the README !

2023-05-22 17:50 UTC, merged

2023-05-22 22:10 UTC, ejalaa12 commented
Thanks for the review and the merge !