Update maintainers
gazebosim/ros_gz pull request #376
Opened 2023-03-20 22:21 UTC by adityapande-1995

Updates maintainers in the contained packages.

2023-03-20 22:23 UTC, ahcorde approved these changes

2023-03-20 22:24 UTC, ahcorde requested changes
Do you mind to add me as a maintaner too ? and also include us in the CODEOWNERS file

2023-03-21 09:38 UTC, ahcorde requested changes
can you remove louise from all package.xml ? and add her as an author?

2023-03-21 09:38 UTC, ahcorde commented on ros_gz_sim_demos/package.xml
>    <maintainer email="louise@openrobotics.org">Louise Poubel</maintainer>
```suggestion
```

2023-03-21 20:00 UTC, adityapande-1995 commented on ros_gz_sim_demos/package.xml
>    <maintainer email="louise@openrobotics.org">Louise Poubel</maintainer>
Done

2023-03-21 20:12 UTC, azeey approved these changes

2023-03-22 13:58 UTC, ahcorde approved these changes

2023-03-22 13:58 UTC, merged