allow converting from/to PoseWithCovarianceStamped
gazebosim/ros_gz pull request #381
Opened 2023-04-11 14:59 UTC by ejalaa12

# 🎉 New feature

Relates to PR #374.

## Summary
ros_gz_bridge allows converting gz.msgs.PoseWithCovariance <-> geometry_msgs.msg.PoseWithCovariance.

However the gz.msgs.PoseWithCovariance also contains a header and stamp. So it could be converted to a geometry_msgs.msg.PoseWithCovariance**Stamped**.

This PR implements that conversion. It is now possible to convert either to/from:

geometry_msgs.msg.PoseWithCovariance
geometry_msgs.msg.PoseWithCovarianceStamped.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2023-04-11 15:00 UTC, ejalaa12 commented
@adityapande-1995 here is the PR you proposed :)

2023-04-24 18:41 UTC, adityapande-1995 requested changes
Thanks for adding this ! Could you update the README file to reflect this change ?

2023-04-27 09:40 UTC, ejalaa12 commented
> Thanks for adding this ! Could you update the README file to reflect this change ? https://github.com/gazebosim/ros_gz/blob/ros2/ros_gz_bridge/README.md

Sure !
I just did it and pushed.

Btw, I went ahead and fixed the [Table header alignement](https://www.pluralsight.com/guides/working-tables-github-markdown) from `| :---: |` to `| :--- |` because this is what you seem to be using.

2023-05-01 18:13 UTC, adityapande-1995 approved these changes

2023-05-01 18:16 UTC, merged