Added messages for 2D Bounding Boxes to ros_gz_bridge
gazebosim/ros_gz pull request #458
Opened 2023-10-27 12:30 UTC by wittenator

# 🎉 New feature

Closes #457

## Summary
I added the bridging of Detection2D and Detection2DArray to AnnotatedAxisAligned2DBox and AnnotatedAxisAligned2DBox_V and vice versa. 

## Test it
WIP

## Checklist
- [X] Signed all commits for DCO
- [X] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [X] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [X] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

2023-10-30 09:22 UTC, ahcorde requested changes

2023-10-30 09:22 UTC, ahcorde commented on ros_gz_bridge/include/ros_gz_bridge/convert/vision_msgs.hpp
> +// Copyright 2018 Open Source Robotics Foundation, Inc.
```suggestion
// Copyright 2023 Open Source Robotics Foundation, Inc.
```

2023-10-30 09:22 UTC, ahcorde commented on ros_gz_bridge/include/ros_gz_bridge/convert/vision_msgs.hpp
> +}  // namespace ros_gz_bridge
```suggestion
  vision_msgs::msg::Detection2DArray & ros_msg);
}  // namespace ros_gz_bridge
```

2023-10-30 09:22 UTC, ahcorde commented on ros_gz_bridge/include/ros_gz_bridge/convert/vision_msgs.hpp
> +template<>
```suggestion
namespace ros_gz_bridge
{
template<>
```

2023-10-30 09:22 UTC, ahcorde commented on ros_gz_bridge/src/convert/vision_msgs.cpp
> +// Copyright 2018 Open Source Robotics Foundation, Inc.
```suggestion
// Copyright 2023 Open Source Robotics Foundation, Inc.
```

2023-10-30 09:22 UTC, ahcorde commented on ros_gz_bridge/src/convert/vision_msgs.cpp
> +template<>
```suggestion
#include "ros_gz_bridge/convert/vision_msgs.hpp"

namespace ros_gz_bridge
{
template<>
```

2023-10-30 09:22 UTC, ahcorde commented on ros_gz_bridge/src/convert/vision_msgs.cpp
> +  auto id = ros_msg.results.at(0).hypothesis.class_id;
we should check here if there is any values availables in the `results` array.

2023-10-30 09:22 UTC, ahcorde commented on ros_gz_bridge/src/convert/vision_msgs.cpp
> +  ros_msg.results.at(0).hypothesis.score = 1.0;
Check if the `results` array has some values. This might crash

2023-10-30 09:22 UTC, ahcorde commented on ros_gz_bridge/src/convert/vision_msgs.cpp
> +  for (auto ros_box : ros_msg.detections) {
```suggestion
  for (const auto & ros_box : ros_msg.detections) {
```

2023-10-30 09:22 UTC, ahcorde commented on ros_gz_bridge/src/convert/vision_msgs.cpp
> +  for (auto gz_box : gz_msg.annotated_box()) {
```suggestion
  for (const auto & gz_box : gz_msg.annotated_box()) {
```

2023-10-30 15:15 UTC, wittenator commented on ros_gz_bridge/src/convert/vision_msgs.cpp
> +  auto id = ros_msg.results.at(0).hypothesis.class_id;
Thanks for the quick review! Should we maybe print a warning when there is nothing in the results array as it is a malformed message? If I am not mistaken, the id in the GZ message will be 0 if it is not explicitly set. Or is there any other way of conveying "None-ness" here?

2023-11-09 09:12 UTC, ahcorde approved these changes

2023-11-09 09:12 UTC, merged