Citadel support
gazebosim/ros_gz pull request #48
Opened 2019-10-22 09:06 UTC by chapulina

* Ignore `ros_ign_point_cloud` until #40 is resolved
* Accept both ign-gazebo 2 and ign-gazebo 3 for the demos
* Other packages not affected, since we're still using `msgs4` and `transport7`

2019-11-26 00:35 UTC, JShep1 requested changes

2019-11-26 00:35 UTC, JShep1 commented on ros_ign_gazebo_demos/README.md
> +* `sendor_msgs/PointCloud2`, through `ros_ign_point_cloud` (See issue #40)
Did you mean `sensor` here?

2019-11-26 00:35 UTC, JShep1 commented on ros_ign_gazebo_demos/README.md
> +* `sendor_msgs/PointCloud2`, through the `ros_ign_bridge` or `ros_ign_point_cloud` (See issue #40)
Same as above

2019-11-26 00:35 UTC, JShep1 commented on ros_ign_gazebo_demos/README.md
> +* `sendor_msgs/PointCloud2`, through `ros_ign_bridge` or `ros_ign_point_cloud` (See issue #40)
Same as above

2019-11-26 00:57 UTC, JShep1 requested changes

2019-11-26 00:57 UTC, JShep1 commented on ros_ign_bridge/CMakeLists.txt
> +  find_package(ignition-msggs4 REQUIRED)
msggs -> msgs

2019-11-26 00:57 UTC, JShep1 commented on ros_ign_bridge/CMakeLists.txt
> +find_package(ignition-transport8 REQUIRED)
`REQUIRED` -> `QUIET`

2019-11-26 00:57 UTC, JShep1 commented on ros_ign_image/CMakeLists.txt
> +find_package(ignition-transport8 REQUIRED)
`REQUIRED` -> `QUIET`

2019-11-26 00:57 UTC, JShep1 commented on ros_ign_image/CMakeLists.txt
> +  find_package(ignition-msggs4 REQUIRED)
msggs -> msgs

2019-11-26 01:11 UTC, claireyywang approved these changes
LGTM other than the typos.

2019-11-26 01:59 UTC, JShep1 requested changes
LGTM! Builds cleanly with `Citadel` and `Blueprint` with all demos working once the suggested changes are made.

2019-11-26 01:59 UTC, JShep1 commented on ros_ign_bridge/CMakeLists.txt
> +  if (NOT ignition-transport7_FOUND)
This if statement can be deleted

2019-11-26 01:59 UTC, JShep1 commented on ros_ign_image/CMakeLists.txt
> +  if (NOT ignition-transport7_FOUND)
This if statement can be deleted

2019-12-05 19:51 UTC, JShep1 approved these changes
LGTM

2019-12-06 01:00 UTC, merged