Undeprecate use of commandline flags
gazebosim/ros_gz pull request #491
Opened 2024-01-29 16:44 UTC by azeey

## Summary

I'm writing a migration guide for Gazebo classic users and using the command line flags since that's what's available in Humble. It's also very closely matched with `gazebo_ros_pkgs` so the migration is a lot easier if we keep the flags. I think it would be best to keep these flags, at least for another ROS release cycle.

 
## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-01-29 16:47 UTC, ahcorde requested changes
Do you mind to create a TODO for the next release ?

2024-01-29 17:03 UTC, mjcarroll approved these changes

2024-01-30 18:35 UTC, azeey commented
> Do you mind to create a TODO for the next release ?

Done in https://github.com/gazebosim/ros_gz/pull/491/commits/7aa366b64cd4c0e6cac5f183735a4f61faef95be

2024-01-30 20:31 UTC, ahcorde approved these changes

2024-01-30 20:31 UTC, merged