Correctly export ros_gz_bridge for downstream targets
gazebosim/ros_gz pull request #503
Opened 2024-02-22 19:17 UTC by mjcarroll

Additionally adds a `test_ros_gz_bridge` target to verify that this behavior is working.  

We could also put our integration tests in here in the long run, but I will leave that to a follow up.

2024-02-22 19:22 UTC, ahcorde requested changes
Do you mind to merge with the `ros2` branch?

2024-02-22 19:35 UTC, ahcorde approved these changes

2024-02-22 19:43 UTC, merged

2024-02-22 19:44 UTC, ahcorde commented
are you going to backport this?

2024-02-23 15:36 UTC, mjcarroll commented
Backports #504 + #505