Make the pose_V to TFMessage conform with ROS2
gazebosim/ros_gz pull request #510
Opened 2024-03-11 18:59 UTC by teyssieuman

# 🦟 Bug fix

The conversion from a gz::msgs::pose_V message to a ros2 geometry_msgs::msg::TransformStamped message what not compatible to make it a proper "tf2" message.

## Summary

## Checklist
- [x] Signed all commits for DCO

2024-03-11 21:33 UTC, azeey commented
I'm not sure why this PR is needed. The `child_frame_id` is properly handled by the conversion from `gz::msgs::Pose` to `geometry_msgs::msg::TransformStamped` in

https://github.com/gazebosim/ros_gz/blob/21d4c2317bbaa1d73260257e27fd61f20eb13ea1/ros_gz_bridge/src/convert/geometry_msgs.cpp#L251-L257

and the `frame_id` is handled in https://github.com/gazebosim/ros_gz/blob/21d4c2317bbaa1d73260257e27fd61f20eb13ea1/ros_gz_bridge/src/convert/std_msgs.cpp#L171-L176

2024-03-13 09:12 UTC, ahcorde requested changes

2024-03-13 09:12 UTC, ahcorde commented on ros_gz_bridge/src/convert/tf2_msgs.cpp
> +    tf.header.frame_id = "world";
not sure about this, maybe we should be able to configure this with a parameter, @azeey or @mjcarroll thoughts?

2024-12-20 17:37 UTC, azeey commented
I'm going to close this PR for lack of activity. @teyssieuman if you still want to make progress on the PR, I'd suggest opening a new one targeting the `ros2` branch. We can then backport to `humble` if the changes are backward compatible. Thanks for the contribution nonetheless.

2024-12-20 17:37 UTC, closed without merging