Add ROS namespaces to GZ topics
gazebosim/ros_gz pull request #512
Opened 2024-03-18 23:05 UTC by Kotochleb

# 🎉 New feature

## Summary
This PR adds the ability to apply ROS node namespace onto GZ topics. This adds option for global namespaces as well as private namespaces. The only missing feature are substitutions, and I am not sure if there is need for now to implement this.

I believe this feature later could be easily ported to Iron and Rolling.

## Test it
In the `config_file` YAML file, create topics as:
```yaml
- topic_name: "chatter"
  ros_type_name: "std_msgs/msg/String"
  gz_type_name: "gz.msgs.StringMsg"
  direction: ROS_TO_GZ

- topic_name: "/chatter_global"
  ros_type_name: "std_msgs/msg/String"
  gz_type_name: "gz.msgs.StringMsg"
  direction: ROS_TO_GZ

- topic_name: "~/chatter_private_ns"
  ros_type_name: "std_msgs/msg/String"
  gz_type_name: "gz.msgs.StringMsg"
  direction: ROS_TO_GZ

- ros_topic_name: "chatter_ros_ns"
  gz_topic_name: "/chatter_ign_global"
  ros_type_name: "std_msgs/msg/String"
  gz_type_name: "gz.msgs.StringMsg"
  direction: ROS_TO_GZ
```

This should create ROS topics:
```bash
$ ros2 topic list
/my_namespace/chatter
/chatter_global
/my_namespace/ros_gz_bridge/chatter_private_ns
/my_namespace/chatter_ros_ns
```
And GZ topics:
```bash
$ ign topic --list
/my_namespace/chatter
/chatter_global
/my_namespace/ros_gz_bridge/chatter_private_ns
/chatter_ign_global
```

2024-03-19 09:17 UTC, ahcorde requested changes

2024-03-19 09:17 UTC, ahcorde commented on ros_gz_bridge/src/ros_gz_bridge.cpp
> +
```suggestion

```

2024-03-19 09:17 UTC, ahcorde commented on ros_gz_bridge/src/ros_gz_bridge.cpp
Alphabetize
```suggestion
#include "bridge_handle_ros_to_gz.hpp"
#include "bridge_handle_gz_to_ros.hpp"

#include <rclcpp/expand_topic_or_service_name.hpp>
```

2024-03-19 09:19 UTC, ahcorde requested changes
CI is failing https://build.ros2.org/job/Ipr__ros_gz__ubuntu_jammy_amd64/79/#showFailuresLink

Do you mind to sign the commit ?

2024-03-19 10:59 UTC, Kotochleb commented
@ahcorde I applied your suggestions and signed the commits

2024-03-19 14:36 UTC, azeey commented
hmm, not sure why this is trying to run `Rpr__ros_gz__ubuntu_noble_amd64` . It should be testing with Humble on Jammy.

2024-03-19 15:17 UTC, Kotochleb commented
@azeey do you think I should just wait for the CI to be solved on your side? It doesn't seem to be broken by my changes

2024-03-19 15:46 UTC, azeey commented
> @azeey do you think I should just wait for the CI to be solved on your side? It doesn't seem to be broken by my changes

Yes, this is unrelated to your PR. Hopefully, we'll have a fix soon.

2024-03-20 09:04 UTC, ahcorde requested changes
Can you add some documentation in the README ?

2024-03-20 10:12 UTC, Kotochleb commented
@ahcorde I added new section about the remapping to the README.md.
I also sort of allowed myself to change `source` commands to have `humble` instead of `galactic`, as this is humble branch. Since it is a very minor change and I am already making changes in the README, I thought it will be fine to push it with this PR.

2024-03-20 17:08 UTC, ahcorde requested changes
some more minor comment, otherwise looks good to me

2024-03-20 17:08 UTC, ahcorde commented on ros_gz_bridge/README.md
> +```
```suggestion
```bash
```

2024-03-20 17:08 UTC, ahcorde commented on ros_gz_bridge/README.md
> +```
```suggestion
```bash
```

2024-03-20 17:08 UTC, ahcorde commented on ros_gz_bridge/README.md
>  ## API
```suggestion
By changing `chatter` to `/chatter` or `~/chatter` you can obtain different results.

## API
```

2024-03-20 17:08 UTC, ahcorde commented on ros_gz_bridge/README.md
> +```
```suggestion
```bash
```

2024-03-20 17:14 UTC, ahcorde approved these changes

2024-03-20 17:27 UTC, merged

2024-03-20 17:28 UTC, ahcorde commented
@Kotochleb thank you for your contribution, do you have some time to do the forward port in `iron` and `rolling`?

2024-03-20 17:31 UTC, Kotochleb commented
@ahcorde you are welcome. I would have time, but it will take me a few more days, as this feature for Humble was something I needed right now. Hopefully I will submit the PRs till end of this week.

2024-03-25 18:29 UTC, ahcorde commented
backports
 - https://github.com/gazebosim/ros_gz/pull/517
 - https://github.com/gazebosim/ros_gz/pull/516