feat: `override_timestamps_with_wall_time` parameter
gazebosim/ros_gz pull request #562
Opened 2024-06-19 09:39 UTC by reinzor

# 🎉 New feature

Closes #546 

## Summary
Stamp all outgoing headers with the wall time if parameter `override_timestamps_with_wall_time` is set to `true`.

## Test it
Start the bridge with the additional parameter `override_timestamps_with_wall_time` set to `true`. Not that the outgoing messages have the wall time stamp and not the gazebo time stamp.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-06-19 14:42 UTC, ahcorde requested changes
code is not compiling https://github.com/gazebosim/ros_gz/actions/runs/9579762345/job/26418501612?pr=562

2024-06-25 14:28 UTC, azeey commented
@Mergifyio update

2024-06-25 18:50 UTC, azeey commented
CI issues should hopefully be fixed after https://github.com/ros2/ros2/pull/1574

2024-07-02 07:46 UTC, Timple commented
Let's re-run them then :slightly_smiling_face:

2024-07-02 16:19 UTC, azeey commented
I just reran it, but I realized the branch is out-of-date. Do you mind merging from `ros2`?

2024-07-03 05:50 UTC, reinzor commented
> I just reran it, but I realized the branch is out-of-date. Do you mind merging from `ros2`?

done

2024-07-08 23:09 UTC, azeey commented
It seems like there are some CI failures. Do the tests pass locally for you?

2024-07-30 06:33 UTC, reinzor commented
> It seems like there are some CI failures. Do the tests pass locally for you?

I am running the tests locally and they seem to fail as well. However, I don't see how this code change would affect the failing tests. Could you help me with this?

2024-07-30 15:32 UTC, azeey commented
The error logs indicated that it was failing to create any of the GZ->ROS bridges. Inspecting the exception with a print statement shows that the problem is that we are redeclaring the `override_timestamps_with_wall_time` parameter. My suggestion is to declare the parameter in https://github.com/gazebosim/ros_gz/blob/4c64bbea8041131b36a84692af7064a4abbfddb4/ros_gz_bridge/src/ros_gz_bridge.cpp#L35 and use `get_parameter` to actually retrieve the value. I would also suggest adding a member variable to `BridgeHandle` that stores the value of the parameter and fetch the parameter in the constructor of `BridgeHandle` instead of modifying the function signature.

2024-07-31 06:23 UTC, reinzor commented
Thanks for your help @azeey ; I updated the PR with the suggestions you mentioned. Not sure about not changing the function signature though. We need to pass this variable to the factory right?

2024-07-31 07:27 UTC, ahcorde requested changes

2024-07-31 07:27 UTC, ahcorde commented on ros_gz_bridge/src/factory.hpp
> +struct has_header : std::false_type
include `<type_traits>`

2024-07-31 07:27 UTC, ahcorde commented on ros_gz_bridge/src/factory.hpp
> +        auto now = std::chrono::system_clock::now().time_since_epoch();
include `<chrono>`

2024-07-31 07:28 UTC, ahcorde commented
> Thanks for your help @azeey ; I updated the PR with the suggestions you mentioned. Not sure about not changing the function signature though. We need to pass this variable to the factory right?

You are targeting `ros2`, we can change the API's here, but if we need to backport this, we should do it in a different way

2024-07-31 12:02 UTC, reinzor commented
> > Thanks for your help @azeey ; I updated the PR with the suggestions you mentioned. Not sure about not changing the function signature though. We need to pass this variable to the factory right?
> 
> You are targeting `ros2`, we can change the API's here, but if we need to backport this, we should do it in a different way

I will leave that up to you as maintainers. Feel free to move the logic to a different place.

2024-07-31 13:01 UTC, ahcorde approved these changes

2024-07-31 13:49 UTC, azeey approved these changes
LGTM! Thanks for iterating. I realized the API change issue is not a problem since none of the changed headers are considered public API. I think this could actually be backported if needed.

2024-07-31 13:50 UTC, merged

2024-08-01 05:22 UTC, reinzor commented
Great thanks! How does this backporting to `jazzy` work; should I just send another PR that cherry-picks [this commit](https://github.com/gazebosim/ros_gz/commit/6daea2caf9f0190f83ec7a73e7ed13307b193029)?

2024-08-01 09:37 UTC, ahcorde commented
https://github.com/Mergifyio backport jazzy