Add support for gz.msgs.EntityWrench
gazebosim/ros_gz pull request #572
Opened 2024-06-27 21:06 UTC by Vtn21

# 🎉 New feature

Closes #566

## Summary

Adds the new ros_gz_interfaces/msg/EntityWrench, with structure compatible with gz.msgs.EntityWrench. This enables the user to apply wrenches to Gazebo entities using ROS topics.

Also implements the ros_gz_bridge mapping between ros_gz_interfaces/msg/EntityWrench and gz.msgs.EntityWrench.

## Test it

Manual testing involves spawning any entity in Gazebo and loading the gz::sim::systems::ApplyLinkWrench plugin to the world SDF. Then, call the ros_gz_bridge to expose the entity wrench topic as follows (YAML syntax):

```yaml
- topic_name: "/world/<world_name>/wrench"
  ros_type_name: "ros_gz_interfaces/msg/EntityWrench"
  gz_type_name: "gz.msgs.EntityWrench"
```

Wrenches are then applied to selected entities using the "/world/<world_name>/wrench" topic.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [x] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-06-27 21:27 UTC, ahcorde requested changes
Can you retarget the PR to `rolling` ? then we can backport this to other branches.

We use mergify to backport PR, there is no need to create a PR for each branch

2024-06-28 14:46 UTC, ahcorde requested changes

2024-06-28 14:46 UTC, ahcorde commented on ros_gz_bridge/README.md
> +| builtin_interfaces/msg/Time                 | ignition::msgs::Time                        |
```suggestion
| builtin_interfaces/msg/Time                 | gz::msgs::Time                        |
```
Please fix the table

2024-06-28 15:03 UTC, ahcorde requested changes

2024-06-28 15:03 UTC, ahcorde commented on ros_gz_bridge/README.md
> +| builtin_interfaces/msg/Time                 | gz::msgs::Time                        |
Not only this one, the rest of item too

2024-06-29 15:56 UTC, Vtn21 commented
Hi @ahcorde , sorry for my delay. While working on merging the PR with the base ```ros2``` branch, I ended up forgetting to signoff a commit and things got messy. I opened another PR checking out directly from the ```ros2``` branch which I believe is better now. Thanks for the support!

2024-06-29 15:56 UTC, closed without merging