Battery demo refactor
gazebosim/ros_gz pull request #633
Opened 2024-11-05 17:29 UTC by caguero

Refactors the `battery` demo leveraging the latest improvements in `ros_gz`. 

* I replaced the previous launch file from Python to XML because I think it's the recommendation (and looks easier) but I'll still keep some of the demos in Python to offer some variety.
* I didn't implement support for running `gzserver` with `-z 1000000`.

## Summary

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-11-06 17:09 UTC, ahcorde approved these changes

2024-11-25 16:23 UTC, ahcorde requested changes
why not the `xml` version ?

2024-11-25 16:38 UTC, caguero commented
> why not the `xml` version ?

We're launching Gazebo with `-z 1000000`. If we move to XML we cannot support it.

2024-12-16 10:41 UTC, ahcorde requested changes
Launch is a Python file no a xml

2024-12-16 10:42 UTC, ahcorde approved these changes

2024-12-16 10:43 UTC, merged