Refactor camera demo
gazebosim/ros_gz pull request #634
Opened 2024-11-05 20:38 UTC by caguero

Refactors the `camera` demo leveraging the latest improvements in `ros_gz`. 

* I replaced the previous launch file from Python to XML.

## Summary

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-11-06 17:10 UTC, ahcorde approved these changes

2024-11-25 16:33 UTC, ahcorde requested changes
When RViz is opened the position of the camera is in the wrong position.

My suggestions here:
  - The sdf file that we are using it's from gz-sim, and we need to define in the camera sensor the `gz_frame_id` to `camera_optical`
  -  Then we need to add a static transfrom 
 ```xml
<node pkg="tf2_ros" exec="static_transform_publisher" args="--frame-id camera_link  --child-frame-id camera_link_optical --roll 1.570796327 --yaw 1.570796327" />
 ```

Let me know if you need some help and I can open a PR with the suggestions

2024-11-27 16:15 UTC, caguero commented
> When RViz is opened the position of the camera is in the wrong position.

My RViz camera looks the same as the one in Gazebo. Is this what you're seeing on your side?

![Screenshot from 2024-11-27 17-13-08](https://github.com/user-attachments/assets/efa9632a-1ace-4005-8959-8eb8e99d31b0)

2024-12-11 16:44 UTC, caguero commented
> When RViz is opened the position of the camera is in the wrong position.

To minimize changes, I used the default camera sensor frame in the static transform publisher so that we don't need to add any frame ids or copy and still work with the default world.

Here's the 3D scene with the updated camera position:

![Screenshot from 2024-12-11 17-44-05](https://github.com/user-attachments/assets/8db179d5-b7e5-44d5-aee2-56ff1dbb3f13)

2024-12-16 10:43 UTC, ahcorde approved these changes

2024-12-18 11:56 UTC, merged