Refactor diff_drive demo
gazebosim/ros_gz pull request #635
Opened 2024-11-06 16:18 UTC by caguero

Refactors the `diff_drive` demo leveraging the latest improvements in `ros_gz`. 

* I replaced the previous launch file from Python to XML.
* I didn't port the QoS settings from the demo yet.

## Summary

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-11-25 16:46 UTC, ahcorde requested changes
we are not publishing the `tf` from Gazebo. 

My suggestion here is to add the tf to the bridge
```yaml
- ros_topic_name: "tf"
  gz_topic_name: "/model/vehicle_green/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
- ros_topic_name: "tf"
  gz_topic_name: "/model/vehicle_blue/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
```

and a static transform for each vehicle:
```xml
<node pkg="tf2_ros" exec="static_transform_publisher" args="--frame-id world  --child-frame-id vehicle_green/odom" />
<node pkg="tf2_ros" exec="static_transform_publisher" args="--frame-id world  --child-frame-id vehicle_blue/odom" />
```

And modify the RViz file to sue the "Fixed frame" as `world` and add the other odometry marker for the green vehicle

2024-11-25 16:46 UTC, ahcorde commented on ros_gz_sim_demos/README.md
> -This demo also shows the use of custom QoS parameters. The commands are
why do you remove this comment?

2024-11-27 16:17 UTC, caguero commented on ros_gz_sim_demos/README.md
> -This demo also shows the use of custom QoS parameters. The commands are
The latest version of the code ([79ece9e](https://github.com/gazebosim/ros_gz/pull/635/commits/79ece9ed0babb7869ede938120f8cd324400e34b)) preserves that block.

2024-11-27 16:36 UTC, caguero commented
> 80d120b



> we are not publishing the `tf` from Gazebo.
> 
> My suggestion here is to add the tf to the bridge
> 
> ```yaml
> - ros_topic_name: "tf"
>   gz_topic_name: "/model/vehicle_green/tf"
>   ros_type_name: "tf2_msgs/msg/TFMessage"
>   gz_type_name: "gz.msgs.Pose_V"
>   direction: GZ_TO_ROS
> - ros_topic_name: "tf"
>   gz_topic_name: "/model/vehicle_blue/tf"
>   ros_type_name: "tf2_msgs/msg/TFMessage"
>   gz_type_name: "gz.msgs.Pose_V"
>   direction: GZ_TO_ROS
> ```
> 
> and a static transform for each vehicle:
> 
> ```
> <node pkg="tf2_ros" exec="static_transform_publisher" args="--frame-id world  --child-frame-id vehicle_green/odom" />
> <node pkg="tf2_ros" exec="static_transform_publisher" args="--frame-id world  --child-frame-id vehicle_blue/odom" />
> ```
> 
> And modify the RViz file to sue the "Fixed frame" as `world` and add the other odometry marker for the green vehicle

Thanks for the suggestion. Added in [80d120b](https://github.com/gazebosim/ros_gz/pull/635/commits/80d120bbe80228557e3dc2bc820c3205b1842d75). Could you give it a try please?

2024-12-16 10:41 UTC, ahcorde requested changes
Added some suggestions here https://github.com/gazebosim/ros_gz/pull/676

2024-12-18 20:12 UTC, ahcorde approved these changes

2024-12-18 20:12 UTC, merged