Set env path
gazebosim/ros_gz pull request #659
Opened 2024-12-03 00:27 UTC by Tacha-S

# 🦟 Bug fix

Fixes #549 

## Summary

I set the environment variables to correctly load plugins when launching with a composable node.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-12-03 05:22 UTC, azeey reviewed
Thanks for the contribution!!
 
This approach works, but only when using the python launch file. It wouldn't work for those using the `gzserver` action from XML. So, could you move these changes to the action (https://github.com/gazebosim/ros_gz/blob/ros2/ros_gz_sim/ros_gz_sim/actions/gzserver.py)?

2024-12-03 14:19 UTC, Amronos commented
I think this PR fixes #630 instead of #549.

2024-12-04 01:00 UTC, Tacha-S commented
> This approach works, but only when using the python launch file. It wouldn't work for those using the gzserver action from XML. So, could you move these changes to the action ([ros2/ros_gz_sim/ros_gz_sim/actions/gzserver.py](https://github.com/gazebosim/ros_gz/blob/ros2/ros_gz_sim/ros_gz_sim/actions/gzserver.py))?

I moved to setting environment variables in [ros2/ros_gz_sim/ros_gz_sim/actions/gzserver.py](https://github.com/gazebosim/ros_gz/blob/ros2/ros_gz_sim/ros_gz_sim/actions/gzserver.py).

> I think this PR fixes https://github.com/gazebosim/ros_gz/issues/630 instead of https://github.com/gazebosim/ros_gz/issues/549.

Oops, it seems I accidentally selected the one above when choosing an issue.
Thank you. I’ve fixed it.

2024-12-04 08:48 UTC, ahcorde requested changes
Do you mind to add some documentation about this ?

2024-12-05 09:31 UTC, ahcorde approved these changes

2024-12-05 22:23 UTC, azeey approved these changes
LGTM!

2024-12-05 22:48 UTC, merged

2024-12-05 22:48 UTC, ahcorde commented
https://github.com/Mergifyio backport jazzy