Updated launch file to use ros_ign_gazebo
gazebosim/ros_gz pull request #82
Opened 2020-06-09 13:53 UTC by ahcorde

This PR builds on top of this other PR #80

This PR update the lanch file to use the launch file inside ros_ign_gazebo

Signed-off-by: ahcorde <ahcorde@gmail.com>

2020-06-12 22:03 UTC, chapulina reviewed
Can we rebase this on top of #80 ? Otherwise it's hard to test if things are working.

Also note that `ros_ign_gazebo_demos/README.md` will need updates too.

2020-06-12 22:03 UTC, chapulina commented on ros_ign_gazebo_demos/launch/air_pressure.launch.py
> +        output='screen'
This doesn't work yet, right? See https://github.com/ignitionrobotics/ros_ign/issues/78

2020-06-12 22:03 UTC, chapulina commented on ros_ign_gazebo_demos/launch/battery.launch.py
> -    )
Is there a reason not to keep this in a variable? It's maybe a bit cleaner?

2020-06-15 21:55 UTC, chapulina commented
#80 and #81 have been merged. I think this needs to be rebased and maybe needs a couple of tweaks.

2020-06-24 17:25 UTC, chapulina requested changes
Before merging, we should make sure that all `ros_ign_gazebo_demos` work with dashing on this branch.

2020-06-24 17:25 UTC, chapulina commented on ros_ign_gazebo_demos/launch/image_bridge.launch.py
> +        executable='image_bridge',
This is only [changing from Foxy](https://index.ros.org/doc/ros2/Releases/Release-Foxy-Fitzroy/#launch-ros), so we can't land it on the `dashing` branch.

2020-06-24 18:49 UTC, chapulina commented
See #85 for a Dashing-compatible version.

2020-06-26 11:08 UTC, ahcorde commented
Related with this issue https://github.com/ignitionrobotics/ros_ign/pull/89

2020-07-01 21:24 UTC, chapulina approved these changes
This is working for me, thanks! I just have some small comments below, we can merge once they're addressed.

2020-07-01 21:24 UTC, chapulina commented on ros_ign_gazebo_demos/launch/air_pressure.launch.py
> -# [ignition.msgs.FluidPressure]
Can we keep this TODO until #78 is fixed?

2020-07-01 21:24 UTC, chapulina commented on ros_ign_gazebo_demos/launch/depth_camera.launch.py
> +                              description='Open RViz.'),
```suggestion
                              description='Open RQt.'),
```

2020-07-01 21:24 UTC, chapulina commented on ros_ign_gazebo_demos/launch/imu.launch.py
> -    pkg_ros_ign_gazebo_demos = get_package_share_directory('ros_ign_gazebo_demos')
This will be needed when RViz is enabled again, maybe we could leave it here commented out?

2020-07-01 21:24 UTC, chapulina commented on ros_ign_gazebo_demos/launch/rgbd_camera.launch.py
>                     '/rgbd_camera/depth_image@sensor_msgs/Image@ignition.msgs.Image'],
Oops, there's some pre-existing issue here, the ROS 2 messages are missing the extra `msgs` namespace

2020-07-02 06:42 UTC, merged